- lib/shared-method.js
- test/shared-class.test.js
/to @ritch 
The PR allows accessType to be configured per shared method to avoid hard-coding accessType mapping of remote methods for ACL. See https://github.com/strongloop/strong-remoting/issues/146.
> Allow accessType to be configured per shared method

- lib/http-invocation.js
- test/http-invocation.test.js
> Ensure Remote-Connector Converts Types in Array

- lib/http-invocation.js
- lib/remote-objects.js
- lib/rest-adapter.js
- test/rest-adapter.test.js
Hooks on invoke are needed to use methods like User login/logout 
in the browser with loopback remotely from loopback-connector-remote.
see https://github.com/strongloop/strong-remoting/issues/150
and https://github.com/strongloop/strong-remoting/issues/105
and https://github.com/strongloop/loopback/pull/943
> Add remote hooks to restAdapter.invoke method

- .jshintrc
- lib/http-invocation.js
- package.json
- test/auth.test.js
This is necessary to allow loopback-connector-remote to support backends that use Digest auth, which is required to allow strong-pm (or any other backend) to support Digest auth.
/cc @sam-github @kraman
> Add proper support for remotes using HTTP authentication

- .jscsrc
- Gruntfile.js
- lib/shared-method.js
- package.json
- test/rest-adapter.test.js
Upgrade grunt-jscs to the latest version.
Fix definition of test files in Gruntfile.js
Allow declaration of multiple variables in a single statement when
the variables are not initialized.
> Fix jscs settings

- lib/remote-objects.js
- test/rest.test.js
to/ @bajtos 
Made following changes for issue#709
- In remote-objects.js Enclosed the call to cur.call with try-catch block
- Added test case to verify that unhandled exceptions, do not crash the server.
Can you please review?
> Catch unhandled error on current method invocation

- .jshintrc
- lib/remote-objects.js
- lib/shared-method.js
- package.json
- test/rest.test.js
- test/shared-method.test.js
If a shared method or a hook handler returns a duck-typed promise, i.e. an object with a `then` method, then the invocation waits until the promise is fulfilled or rejected.
Connect strongloop/loopback#418
/to @raymondfeng @ritch please review
> Support Promise-returning method and hooks

- lib/shared-method.js
- test/shared-method.test.js
A follow-up for #179, connect strongloop/loopback#418
Comparison of callback and promise APIs:
```
callback(null, value) <===> resolve(value)
callback(null, arg1, arg2) <===> resolve([arg1, arg2])
```
/to @raymondfeng @ritch please review
> Allow promises to resolve with a single arg

- lib/http-invocation.js
- lib/remote-objects.js
- lib/rest-adapter.js
- test/auth.test.js
This adds a new feature (built on top of the existing auth support). Using `remotes.auth` you can now provide basic, bearer, and digest authorization (even after `remotes.connect()`).
This patch introduces the api (the `remotes.auth` property) and support in `HttpInvocation`. It maintains backwards compatibility by setting `remotes.auth` using the url provided in `remotes.connect()`.
The key new feature is that authorization can be set at any time and requests afterward will honor this setting. This makes it possible to do this:
```js
remotes.connect('http://localhost:3000');
remotes.invoke('User.login', [{
username: 'foo',
password: 'bar'
}], function(err, result) {
remotes.auth = {
bearer: result.accessToken
};
});
```
...all subsequent invocations will be signed with the token.
/to …
> Add remotes.auth / authorization support

- lib/http-context.js
- test/rest.test.js
to / @bajtos -
In reference to
1) Strong-remoting issue - https://github.com/strongloop/strong-remoting/issues/175 , and
2) LB issue - https://github.com/strongloop/loopback/issues/416
I've made changes to retain non-200 status, when no content is sent.
Can you please review?
> Preserve non-200 status when no content will be sent

- lib/shared-method.js
- test/rest.test.js
Before this patch, a hit like `GET /endpoint?fooArray=` would, if `arrayItemDelimiters` were used, resolve `fooArray` with the value `['']`.
This is undesirable - I see two options for what an empty value should serialize to for an array arg:
1. `undefined`,
2. `[]`.
I went with `2` because I think `?key=` has a different meaning than `?`, since you might really want to pass the empty array instead of undefined.
> Coerce empty string into empty array with arrayItemDelimiters.

- package.json
Remove the following packages:
- cors
- js2xmlparser
See https://github.com/strongloop/loopback/issues/989
/cc @BerkeleyTrue
> browser: remove packages used by server only

- lib/remote-objects.js
/to @bajtos 
/cc @BerkeleyTrue
> Do not require instanceof check for type assertion

- lib/remote-objects.js
- test/rest.test.js
Example usage:
// Do something after the `speak` instance method failed.
remotes.afterError('dog.prototype.speak', function(ctx, next) {
console.log('Cannot speak!', ctx.error);
next();
});
// Modify all returned errors
remotes.after('**', function(ctx, next) {
ie (!ctx.error.details) ctx.result.details = {};
ctx.error.details.info = 'intercepted by a hook';
next();
});
// Report a different error
remotes.after('dog.prototype.speak', function(ctx, next) {
console.error(ctx.error);
next(new Error('See server console log for details.'));
});
Connect to #189 
/cc @raymondfeng @fabien
> Implement "afterError" hook

- lib/http-invocation.js
- test/http-invocation.test.js
Most notably always set `err.statusCode`.
Connect to strongloop/loopback#1166
> Forward invocation error details

- lib/http-context.js
- test/rest.test.js
Set "ctx.ctorArgs" to the arguments passed to a constructor method.
Connect to strongloop/loopback#1276
/to @ritch please review.
I need this change in order to obtain the instance id in strong-express-metrics via `req.remotingContext.ctorArgs.id`
> http-context: save "ctorArgs" on the context

- lib/http-context.js
- lib/shared-method.js
- test/http-context.test.js
- test/rest.test.js
This moves the `arrayItemDelimiters` configuration into http-context.js,
as it is an HTTP implementation detail like querystring parsing and is
not generalizable to remote methods exposed in other ways.
This PR also makes argument coercion more robust for `any`, `object`,
and `array` types.
I was having an issue with single array arguments being coerced improperly
to numbers - for example, with accepts type of `['string']`, input like `'123456'`
was being coerced to the number `123456`. It should be coerced to `['123456']`.
> Fix improper type coercions, especially on array types.

- .travis.yml
Based on the discussion in #195, I would like to enable Travis CI for this project.
Benefits:
- Anonymous access to build results - contributors see why their pull request failed the build
- The build fails whenever `npm build` fails. This allows us to control the acceptance criteria, most notably the build will fail on linter errors.
Close #195
/cc @rmg @raymondfeng @STRML
> Enable Travis CI for this project

- lib/shared-method.js
- test/rest.test.js
Before this patch, when sending an array to an argument of type "object" or "any", the value was flattened and the first item was used instead of the array.
This patch fixes the issue by omitting recursive coersion when the target type is not an array.
See #196 that introduced the regression.
/cc @STRML @XinV
> Fix array coercion for non-array target type

- lib/shared-method.js
- test/rest.test.js
- Modify `coerceAccepts()` to be more strict about the argument value matching the requested argument type.
- Modify the converter to return primitive types (e.g. "number 3") instead of object types (e.g. "Number(3)").
- Reject argument values that don't match target type even after the conversion was applied (HTTP status code 400 is returned in such case).
- Improve test failure messages by reporting errors from `object.invoke()` instead of failing on an assertion that expected successful invocation.
Connect to strongloop-internal/scrum-loopback#243
/to @ritch @raymondfeng please review
/cc @STRML
> Tighten coercion and type checks in SharedMethod

- lib/shared-method.js
- test/rest.test.js
- Use "any" instead of "array" in the unit test to make it easier
to understand what's happening under the hood.
- Rename "targetIsArray" to "targetTypeIsArray".
This is a follow-up for #204.
/cc @STRML
> Cleanup in coercion code

- lib/shared-method.js
- test/shared-method.test.js
Support `type: 'array'` as a syntactic sugar for `type: ['any']`.
Connect to strongloop/loopback#1327
See also #209 
/cc @PradnyaBaviskar @fabien
> Support arg type "array"

- README.md
- lib/remote-objects.js
- test/authorize-hook.test.js
/to @raymondfeng 
/cc @fabien @bajtos 
This pull request adds a new hook that is executed in the following order:
1. invokeMethodInContext
2. **authorization hook**
3. before hooks
4. method
5. after hooks
Here is a basic example implementing the hook:
```js
remotes.authorization = function(ctx, next) {
// you must callback with an error to cancel the invokation
next(new Error('denied'));
}
```
> Add authorization hook

- lib/shared-method.js
- test/rest.test.js
@bajtos, 
In reference to https://github.com/strongloop/loopback/issues/1327, ```accepts: { arg: 'arg', type: 'array' }```, worked out of the box, without me requiring to make any changes!
I've just added test cases to verify target type ```array```
Can you please review?
> add test to verify target type array

- test/rest.test.js
Fixes 'express deprecated res.send(status, body): Use res.status(status).send(body) instead'
> Rest Test: fixed express deprecation warning

- lib/http-context.js
- test/http-context.test.js
> HttpContext: do not lowercase type when resolving dynamic converter

- lib/http-context.js
- lib/http-invocation.js
- lib/rest-adapter.js
- lib/shared-method.js
- package.json
- test/streams.js
This PR adds support for returning object mode `ReadableStream`s.
connect to strongloop/strong-remoting#214
Using HTTP `ReadableStream`s are piped to the `res` using https://github.com/dominictarr/mux-demux. This allows for `stream.on('error')`s to be sent using the multiplexed NL separated JSON protocol.
I would still like to add the same exact capability using multipart responses.
/to @bajtos 
/cc @raymondfeng @kraman @rmg (noticed you had used mux-demux)
> Add object mode ReadableStream support

- lib/shared-method.js
Introduced in 4d96596
@crandmck I tried to only wrap the long lines, but I had to take some liberties with the one particularly long URL (including replacing it with a Confluence generated short URL), so you are probably the best to review.
/cc @ritch @raymondfeng because linting is part of this module's tests, doc changes can break the build. For that reason I recommend doc changes go through the PR process so that they can at least be linted before merging.
> fix long lines in docs that were failing jshint

- lib/http-invocation.js
/to @raymondfeng 
This fixes https://github.com/strongloop/strong-remoting/issues/229
Without setting the `req.protocol` the browserify implementation of `http` incorrectly falls back to the `window.location.protocol` (which is `file:`).
> Explicitly set req.protocol

- lib/shared-method.js
We should be careful with the `raw` size to call traverse, here because this use case is edge one, so I think the inspect call might have too much consumes on normal remote routing.
R= @ritch 
/cc @raymondfeng
> verify the accepts size <= 5000

- lib/http-context.js
Small patch that removes the following warnings:
```
express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:587:17
```
```
express deprecated res.send(status): Use res.sendStatus(status) instead node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:593:13
```
> Remove deprecation warning for res.send()

- package.json
The recently released version jayson@1.2.1 introduced a breaking change
in https://github.com/tedeh/jayson/commit/dc0a13dc4 which is causing
our json-rpc adapter to fail, because we are passing a zero-argument
wrapper function to jayson.
This commit is changing the jayson dependency to strict version 1.2.0, which is the latest
version working for us.
/to @ritch @raymondfeng please review
> Use strict jayson version to prevent regression

- lib/jsonrpc-adapter.js
- package.json
- test/jsonrpc.test.js
/to @ritch @bajtos 
See https://github.com/tedeh/jayson/commit/dc0a13dc4e50880478a446eb682a75f36ef27e3d
> Generate wrapper function with same params as the original one

- lib/jsonrpc-adapter.js
This has to be done because when we run the tests with coverage the
function body gets mangled by instrumentation and the string
replacements fail horribly. The end result is the generated function
ends up not even being valid JavaScript and the tests then fail for
obvious reasons.
> stringify mockWrapper so we can generate coverage

- lib/shared-class.js
- test/shared-class.test.js
> Add options to `sharedClass.methods()` for including all methods

- lib/dynamic.js
- lib/http-coerce.js
- lib/http-context.js
- lib/http-invocation.js
- test/http-context.test.js
- test/type.test.js
This fixes a number of subtle bugs and restricts "sloppy"
argument coercion (e.g. 'true' to the bool true) to string-only
HTTP datasources like querystrings and headers.
* Fixes #223 (coerced Number past MAX_SAFE_INTEGER)
* Possible fix for #208
> Refactor and rework http coercion.

- lib/rest-adapter.js
- test/rest.test.js
options.handleErrors = false will allow the RestAdapter error handler
to be bypassed
See: https://github.com/strongloop/loopback/issues/445#issuecomment-147722977 for discussion
@bajtos does this look ok?
> Modify RestAdapter to allow disabling errorHandler

- lib/shared-method.js
- test/shared-method.test.js
Boolean comparisons don't work like that - as written it's not possible to actually make the `documented` flag stick.
> Fix incorrect boolean logic on shared-method's `documented` flag.

- lib/http-context.js
- test/rest.test.js
- Add test case to make sure default stays as `application/json`
- Add test case to make sure it retains specified content-type
- seperate logic of figuring out what to send and sending it
Connected to strongloop/strong-remoting/issues/258
> Retain accepted content-type with no-content

- lib/http-context.js
- test/rest.test.js
To take wrapperElement as an option in remoteMethod setup 
```yaml
{
returns: { 
root: true,
xml: {wrapperElement: 'a'}
},
http: { path: '/' }
}
```
Objective is to allow user to produce output as follow 
```xml
<a>1</a>
```
Fixes #262
connected to strongloop/strong-remoting/issues/262
> To allow user to customize the root element of xml output

- lib/context-base.js
- lib/http-context.js
- lib/remote-objects.js
- lib/rest-adapter.js
- package.json
Create `ContextBase` - a base class for all Context objects where we can put methods shared by all contexts.
Move `remotes.getScope` to `ContextBase.prototype.getScope` as it belongs there more naturally and will make it easier to access scope in hooks that can access the `ctx` object only.
Connect to strongloop-internal/scrum-loopback#729
@raymondfeng @ritch please review
> Extract ContextBase and ctx.getScope()

- lib/remote-objects.js
- lib/rest-adapter.js
- package.json
- test/phase-handlers.test.js
**0) 	Simplify invokeMethodInContext**
Deprecate `invokeMethodInContext(ctx, method, cb)` in favour of simpler
`invokeMethodInContext(ctx, cb)`.
**1) Add remote invocation phases**
Rework "invokeMethodInContext" to use a concept of phases that allows
external components a more fine-grained way for extending built-in
functionality.
The new API is exposed on `remotes.phases`, which is an instance
of PhaseList from loopback-phase.
There are two built-in phases available: "auth" and "invoke".
Hooks registered via `remotes.authorization`, `remotes.before` and
`remotes.after` are invoked in "auth", "invoke:before" and
"invoke:after" phases.
Here is the complete order in which different hooks/handler are called:
- hook "authorization"
- phase handlers "auth"
- hook "remotes.before"
- phase …
> Remote invocation phases

- lib/remote-objects.js
- test/rest.test.js
Fix `RemoteObjects.prototype.invokeMethodInContext` to trigger afterError
hooks only when there was an invocation error.
This bug was introduced recently by #279.
> Do not call "afterError" on success

- lib/http-context.js
- lib/shared-method.js
- test/rest.test.js
1) Fix handling of return args with `http.target:header`.  Arguments mapped to a response http header should not be included in the response body.
2) Allow users to specify `{ type: 'file', root: true }` for the single argument that will be sent directly as the response body.
The following values are supported for file the file argument:
- String
- Buffer
- ReadableStream (anything that exposes .pipe() method)
Example usage:
```js
MyModel.download = function(cb) {
// this can be for example http.request()
getTheStreamBody(function(err, stream) {
if (err) return cb(err);
// stream can be any of: string, buffer, ReadableStream (e.g. http.IncomingMessage)
cb(null, stream, 'application/octet-stream');
});
}
MyModel.remoteMethod('download', {
isStatic: true,
returns: [
{ arg: 'body', type: …
```
> Add support for "file" return args

- README.md
- test/rest.test.js
Fix typo 'opionated' to 'opinionated'
Should fix doc too.
https://docs.strongloop.com/display/public/LB/Strong+Remoting
> Fix typo 'opionated' to 'opinionated'

- lib/rest-adapter.js
- test/rest.test.js
Temporary fix for strongloop/loopback#2123
Connect to strongloop/loopback#2123
> Handle array of errors.

- lib/http-context.js
- test/streams.js
Connect to strongloop/angular-live-set#10
Backport of #294 to 2.x
> Set to no compression when using change stream

- lib/http-invocation.js
- lib/rest-adapter.js
- test/rest-adapter.test.js
This patch includes:
* Implement `getEndpoints` which returns an array of objects, showing verbs and paths
* Deprecate `getHttpMethod`
* Deprecate `getFullPath`
/to: @bajtos
> Implement getEndpoints

- lib/http-invocation.js
- lib/rest-adapter.js
- test/rest-adapter.test.js
* Implement getEndpoints
* Deprecate getHttpMethod
* Deprecate getFullPath
Connect to https://github.com/strongloop/strong-remoting/pull/305
> Implement getEndpoints()

- 3.0-RELEASE-NOTES.md
- lib/rest-adapter.js
- package.json
- test/rest.browser.test.js
- test/rest.test.js
Using new strong-error-handler for rest-adapter
connect to https://github.com/strongloop-internal/scrum-loopback/issues/852
> [SEMVER-MAJOR] Implement strong error handler for rest-adapter

- test/rest-coercion.test.js
- test/rest-coercion/README.md
- test/rest-coercion/_jsonbody.context.js
- test/rest-coercion/_jsonform.context.js
- test/rest-coercion/_urlencoded.context.js
- test/rest-coercion/jsonbody-any.suite.js
- test/rest-coercion/jsonbody-array.suite.js
- test/rest-coercion/jsonbody-object.suite.js
- test/rest-coercion/jsonform-any.suite.js
- test/rest-coercion/jsonform-array.suite.js
- test/rest-coercion/jsonform-boolean.suite.js
- test/rest-coercion/jsonform-date.suite.js
- test/rest-coercion/jsonform-number.suite.js
- test/rest-coercion/jsonform-object.suite.js
- test/rest-coercion/jsonform-string.suite.js
- test/rest-coercion/urlencoded-any.suite.js
- test/rest-coercion/urlencoded-array.suite.js
- test/rest-coercion/urlencoded-boolean.suite.js
- test/rest-coercion/urlencoded-date.suite.js
- test/rest-coercion/urlencoded-number.suite.js
- test/rest-coercion/urlencoded-object.suite.js
- test/rest-coercion/urlencoded-string.suite.js
An integration test suite describing and verifying argument coercion in REST.
```
1230 passing (3s)
```
(see https://github.com/strongloop-internal/scrum-loopback/issues/706#issuecomment-217371058 for more information)
In this pull request, I am describing the current behaviour in the `master` branch. My intention is to run the test suite against different strong-remoting versions to find differences, I'll post results later.
> In order to discover all breaking changes and document the new behaviour, we should write an extensive integration test suite that can be run against different versions of strong-remoting. Here is an initial draft for inspiration: https://gist.github.com/bajtos/b85e53a79ba06671e08d2013acccc611 Versions to run the suite against: v2.16.0, v2.16.1, latest 2.x, master …
> Test rest coercion

- lib/remote-objects.js
- lib/rest-adapter.js
- test/helpers/shared-objects-factory.js
- test/rest.test.js
Return 401 Not Authorized when making an unauthorised request to a prototype method for a model instance that does not exist.
Potentially breaking change affecting prototype methods:
Hooks registered before "invoke" phase (i.e. "auth" phase and any custom
phases inserted before "invoke") will be called even when the model
instance was not found. The property "ctx.instance" will be undefined
in such case, hook handlers must account for this case.
This is an alternative to #315 that may have less breaking changes.
Connect to #311
@ritch please review.
> Prioritise auth errors over sharedCtor errors

- lib/shared-method.js
- test/rest-coercion/jsonform-integer.suite.js
- test/rest-coercion/urlencoded-integer.suite.js
- test/rest.test.js
- test/shared-method.test.js
all types of numbers, in Javascript, are of only one dataType: `Numbers`.
~~This is a POC~~ Patch to fix #317.
~~Note: Breaks few test cases on local~~
Connect to #317
> Introduce support for integer datatype

- lib/shared-method.js
- test/rest-coercion/jsonform-integer.suite.js
- test/rest-coercion/urlencoded-integer.suite.js
- test/rest.test.js
- test/shared-method.test.js
There is  single datatype in Javascript for
representing numbers: i.e. `numbers`. This is a
patch to fix strong-remoting#317 - a feature
to support data type: `integer`. Includes
following changes:
- Update `convertValueToTargetType()` &
`convertToBasicRemotingType()`
- Update `SharedMethod.getType()`
- Make `integer` check strict by-default.
i.e. If argument and/or returned values are
decimal or `> MAX_SAFE_INTEGER`, for
argument: send `400`, for returns: send
`500`
- Rework `convert` method to ignore all arrays
except "array of integers"
- Add tests to rest-coercion integration
tests
- Update test cases for integer data type
- Update shared-method.js to include
support for Node v.0.10.x
This is a back-port of #323
Connect to #317
> Introduce support for integer datatype [backport to 2.x]

- lib/shared-class.js
- lib/shared-method.js
This is a partial revert of #329 that added globalization of `assert` messages, which caused performance degradation (strong-globalize is rather slow ATM, see https://github.com/strongloop/strong-globalize/issues/66).
see also #331
cc @0candy @superkhau @deepakrkris
> Revert globalization of assert() messages

- lib/shared-class.js
- lib/shared-method.js
This is a partial revert of #330 that added globalization of `assert` messages, which caused performance degradation (strong-globalize is rather slow ATM, see https://github.com/strongloop/strong-globalize/issues/66).
cc @0candy @superkhau @deepakrkris
> Revert globalization of assert() messages [2.x]

- test/shared-class.test.js
* Remove the usage of deprecated methods in shared-class.test.js
Also it needs to be back-ported.
/to: @bajtos
> Remove the usage of deprecated methods

- test/shared-class.test.js
* Remove the usage of deprecated methods in shared-class.test.js
/cc: @bajtos 
Backport from strong-remoting/#333
> Remove the usage of deprecated methods [2.x]

- lib/shared-class.js
- lib/shared-method.js
- test/shared-class.test.js
- test/shared-method.test.js
This is a back-port of #275 excluding the deprecation warnings.
If we included deprecation warnings, then I think tools like loopback-swagger and loopback-sdk-angular will start reporting these deprecations, because IIRC they are still using the old API. Thus I think it's better to buy us more time by not deprecating the old methods yet.
@0candy please review
cc @Amir-61 @davidcheung
> Add new API for finding/disabling remote methods

- test/rest.test.js
The latter is case-sensitive and expects header names in lower-case.
See also the discussion in #293 
@STRML please review
> Fix tests to use res.get instead of res.headers

- 3.0-RELEASE-NOTES.md
- lib/shared-method.js
- test/shared-method.test.js
Change the format of Date "returns" arguments from the output of `.toString()`, which produces values in local timezone, to the output of `.toJSON()`, which produces values in GMT.
Before:
{
"$type": "date",
"$data": "Thu Jan 01 1970 01:00:00 GMT+0100 (CET)"
}
Now:
{
"$type": "date",
"$data": "1970-01-01T00:00:00.000Z"
}
Connect to strongloop/loopback#1990
@ritch please review
@gunjpan @richardpringle @deepakrkris PTAL too
Note: in the issue strongloop/loopback#1990, I am proposing a more radical change. Unfortunately, it also requires more time which we don't have right now.
> [SEMVER-MAJOR] Fix Date serialization

- test/rest-coercion/urlencoded-any.suite.js
- test/rest-coercion/urlencoded-array.suite.js
- test/rest-coercion/urlencoded-integer.suite.js
- test/rest-coercion/urlencoded-number.suite.js
- test/rest-coercion/urlencoded-string.suite.js
Add tests describing behaviour for numbers with a leading zero, see https://github.com/strongloop/strong-remoting/issues/143.
- When the argument's type is `any`, strong-remoting will treat integer numbers starting with `0` as string, e.g. `0668` will preserve the leading zero. However, floats are still converted to numbers, e.g. both `0.42` and `00.42` are converted to a number.
- When the argument's type is `number` or `integer`, strong-remoting will treat integer numbers starting with `0` as numbers and discarding any extra leading zeroes.
@richardpringle @Amir-61 could one of you please review?
Connect to #312
> Add tests for rest-coercion of numbers starting with a leading zero

- test/rest-coercion/urlencoded-any.suite.js
- test/rest-coercion/urlencoded-array.suite.js
- test/rest-coercion/urlencoded-integer.suite.js
- test/rest-coercion/urlencoded-number.suite.js
- test/rest-coercion/urlencoded-string.suite.js
Add tests describing behaviour for numbers with a leading zero, see https://github.com/strongloop/strong-remoting/issues/143.
- When the argument's type is `any`, strong-remoting will treat integer numbers starting with `0` as string, e.g. `0668` will preserve the leading zero. However, floats are still converted to numbers, e.g. both `0.42` and `00.42` are converted to a number.
- When the argument's type is `number` or `integer`, strong-remoting will treat integer numbers starting with `0` as numbers and discarding any extra leading zeroes.
Forward-port #346
Connect to #312
> Add rest-coercion tests for zero-prefixed numbers

- 3.0-RELEASE-NOTES.md
- lib/types/date.js
- test/rest-coercion/urlencoded-array.suite.js
- test/rest-coercion/urlencoded-date.suite.js
When converting a value coming from a string source like querystring to a date, and the value is a timestamp (i.e. an integer), we treat the value as a number now.
That way the value "0" always produces "1970-01-01T00:00:00.000Z" instead of some date around 1999/2000/2001 depending on server timezone.
Connect to #238
@Amir-61 @richardpringle please review
cc @STRML @ritch
> [SEMVER-MAJOR] Fix rest-coercion of timestamp strings

- 3.0-RELEASE-NOTES.md
- lib/looks-like-json.js
- lib/types/any.js
- lib/types/array.js
- lib/types/object.js
- test/rest-coercion.test.js
- test/rest-coercion/_custom-class.context.js
- test/rest-coercion/_jsonbody.context.js
- test/rest-coercion/_jsonform.context.js
- test/rest-coercion/_urlencoded.context.js
- test/rest-coercion/jsonbody-object-type.suite.js
- test/rest-coercion/jsonbody-object.suite.js
- test/rest-coercion/jsonform-object-type.suite.js
- test/rest-coercion/jsonform-object.suite.js
- test/rest-coercion/urlencoded-object-type.suite.js
- test/rest-coercion/urlencoded-object.suite.js
- test/rest.test.js
- Reject array/date values for object arguments
- Add rest-coercion tests for custom object types
This patch builds on top of recently landed #343
Connect to #312
Connect to strongloop-internal/scrum-loopback#974
Connect to strongloop-internal/scrum-loopback#885
@Amir-61 or @richardpringle please review
cc @ritch @STRML
> [SEMVER-MAJOR] Fix object type conversion

- lib/http-context.js
- test/rest.test.js
Fix the detection of JSON content type used to decide whether sloppy
coercion should be applied, so that it correctly supports values with
parameters. For example:
application/json;charset=UTF-8
Connect to #267
@richardpringle please review
cc @ebourmalo
> Detect JSON content-type with parameters

- 3.0-RELEASE-NOTES.md
- lib/jsonrpc-adapter.js
- lib/rest-adapter.js
- package.json
- test/rest.test.js
Following the discussion in https://github.com/strongloop/strong-remoting/pull/293, I would like to revisit the way how CORS is configured in LoopBack applications.
There are two types of applications that are commonly built using LoopBack, and each type has different requirements when it comes to CORS.
1. Public facing API servers serving a variety of clients. CORS should be enabled to allow 3rd party sites to access the API server living on a different domain than the client(s).
2. API+[SPA](https://en.wikipedia.org/wiki/Single-page_application) sites where both the API server and the SPA client live on the same domain and the API should be locked down to serve only its own browser clients, i.e. CORS must be disabled.
So far, we were enabling CORS by default to make it easy to build …
> [SEMVER-MAJOR] Remove built-in CORS middleware

- lib/shared-method.js
When an argument provides "http" mapping as a custom function, then we should not traverse the return value to detect buffers and dates. The return value could be a complex object, e.g. the full remoting context, in which case the traversal takes too long (in order of seconds!).
I discovered this issue while playing with a solution for injecting context via `options` argument (see https://github.com/strongloop/loopback/issues/1495 and the pull request https://github.com/strongloop/loopback/pull/2762).
@ritch @richardpringle or @deepakrkris please review
> Don't convert arg values returned by http function

- lib/shared-method.js
When an argument provides "http" mapping as a custom function, then we should not traverse the return value to detect buffers and dates. The return value could be a complex object, e.g. the full remoting context, in which case the traversal takes too long (in order of
seconds!).
Back-port #355
> Don't convert arg values returned by http function [2.x]

- lib/jsonrpc-adapter.js
- lib/rest-adapter.js
- test/auth.test.js
- test/authorize-hook.test.js
- test/jsonrpc.test.js
- test/phase-handlers.test.js
- test/rest-adapter.test.js
- test/rest-coercion.test.js
- test/rest.browser.test.js
- test/rest.test.js
- test/streams.js
- test/type.test.js
Push the responsibility of enabling/configuring CORS back to the application developer.
Back-port #352
@richardpringle or @deepakrkris please review
> Deprecate built-in CORS middleware

- lib/remote-objects.js
- test/rest.test.js
Fix the code to correctly recurse and invoke next hooks after the promise returned by the first hook callback was resolved.
The issue was discovered by @tvdstaaij in https://github.com/strongloop/loopback/pull/2751
@gunjpan @richardpringle or @deepakrkris please review
> Fix support for hooks returning a Promise

- lib/http-context.js
- lib/shared-method.js
- test/http-context.test.js
If you have a Loopback model called `File` you'll receive following error when it is set as a return type: `Error: Cannot create a file response from object`
In other words, because `file` is now a reserved keyword with a very specific response handling logic, and `File` is lowercased during normalization into `resultType`, the error above would prevent any Loopback being named `File`. This introduced a breaking change for my apps.
This is loosely related to #318 but in the above case, it's actually not desirable to return a file (buffer/stream) response. Perhaps a more specific keyword than simply `file` would have been better in hindsight.
See also: https://github.com/strongloop/strong-remoting/commit/a85068ef1122751efbbf3e9b2a1b9439ae70fa3f#commitcomment-19410422
@bajtos …
> Distinguish between "file" and "File" result types

- package.json
Due to a recent release of 2.5.10 which broke node 10/12 support
this commit locks down dependency before 2.5.11 is released
as some registry will still pick up unpublished version (2.5.10)
See http-auth/http-auth@0097ed6195986942a65e14b38b3f30281c9f6435
----
edit found out this is causing node 10/12 to fail too
http-auth/apache-md5@4f3b24d3d382851ab2b72a4132f73a8311473856 😢
> lockdown dependency for http-auth

- package.json
backport of #374 
Due to a recent release of 2.5.10 which broke node 10/12 support
this commit locks down dependency before 2.5.11 is released
as some registry will still pick up unpublished version (2.5.10)
2.4.11 is released with apache-md5, apache-crypt locked down
See http-auth/http-auth/commit/0097ed6195986942a65e14b38b3f30281c9f6435
> [backport #374] lockdown dependency for http-auth

- lib/http-context.js
- lib/shared-method.js
- lib/type-registry.js
- lib/types/any.js
- lib/types/array.js
- lib/types/boolean.js
- lib/types/date.js
- lib/types/integer.js
- lib/types/number.js
- lib/types/object.js
- lib/types/string.js
- test/rest-coercion/jsonbody-object-type.suite.js
- test/rest-coercion/jsonbody-object.suite.js
- test/rest-coercion/jsonform-object.suite.js
fixes https://github.com/strongloop/strong-remoting/issues/360
In loopback 2.x endpoints supported batch create which passes
an Array of Objects into the endpoint that expects Objects,
this is nolonger allowed in 3.x's stricter coercion
In order to maintain backwards compatiability, this is a short term
fix to allow endpoints to accept Array of Objects with the allowArray
> allowArray flag for remoteObject `accept`

- lib/shared-method.js
Trying to set value on a read only variable fails on older web views with the following error:
```
["Error group: EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot assign to read only property 'MAX_SAFE_INTEGER' of function Number() { [native code] }"]
```
I have added some guard to make sure it's only set if undefined. This issue was noticed while running on Android 5.0 web views. Works on Android 6.
> Stop changing read-only Number property

- lib/http-invocation.js
- test/http-invocation.test.js
Stringify query params which are objects in a way in which empty ararys
are preserved instead of removed (default querystring implementation).
fix: https://github.com/strongloop/strong-remoting/issues/324
> Stringify query params which are objects as JSON

- lib/type-registry.js
- test/type-registry.test.js
Arguments of `{ type: 'file' }` are handled specially by strong-remoting and don't go through the usual TypeConverter path.
This causes problems in LoopBack applications with a model called "File", which registers a type converter for "file" (the name is case insensitive).
In this patch, we are modifying TypeRegistry to throw an error when the caller attempts to override the built-in "file" type.
Connect to strongloop/loopback#2554
> On the second thought, I think we should add `file` to the list of reserved types and disallow developers to create models called `File`, starting with LoopBack 3.0. It is already not possible to create models like `Object` or `Number`, therefore I think it makes sense to extend this rule to `File` too.
> I believe this will require the smallest amount of …
> Refuse to override builtin file type

- lib/http-invocation.js
- test/http-invocation.test.js
This is a backport of this PR: https://github.com/strongloop/strong-remoting/pull/325. I've cherrypicked the commit and so I've added the refactorings which were made in the test file as well.
@gunjpan - check it out :)
> Stringify query params which are objects as JSON [2.x]

- lib/shared-class.js
- test/shared-class.test.js
For https://github.com/strongloop/loopback/issues/1936
> Disable remote method by alias

- lib/rest-adapter.js
- test/rest.test.js
the defaultHandler always res.sends an object
therefore make sense to always set response header as such
related to https://github.com/strongloop/loopback-component-storage/pull/179
> Rest-adapter errorHandler set content-type `json`

- package.json
Changes to `package.json` for LB2 LTS release.
> Prepare for 2.x LTS

- .gitignore
- .nycrc
- .travis.yml
- package.json
- Fix Travis-CI platforms - drop io.js, add Node 4 and 6
- Sync package scripts with master
backport #401:
- Modify `npm test` to run all tests with code coverage enabled via `nyc`
- Add a new script `npm run coverage` to report the coverage to coveralls.io
- Add a Travis hook `after_success` to run the npm script reporting the coverage
> Add nyc coverage, report data to coveralls.io [2.x]

- lib/rest-adapter.js
- test/rest-adapter.test.js
This function in RestAdapter is slow due
to creating RestMethods each time.
This can be cached initially, and rechecked
if the entry was not found.
getRestMethodByName was identified as slow performing when syncing many items across many models. The reason is that each call will iterate through all classes, and create new RestMethods which is slow. 
This optimisation will create a name->RestMethod cache map which is initialised the first time it is called. This way, the look ups are fast. If there is a cache miss, then it will try to refresh the cache (if it hasn't been refreshed already).
- None
> Cache getRestMethodByName to improve performance of remote invocations

- lib/shared-method.js
- test/shared-class.test.js
Allow strong-remoting dependents like loopback to define custom metadata for shared methods.
- connect to strongloop/loopback#382
cc @strongloop/sq-lb-epitome
> Preserve custom remoting metadata (shared methods)

- lib/http-context.js
- test/rest.test.js
HTTPContext will crash if `_format` is present but not a string.
#396
> fix crash on invalid `_format` type. Fixes #396

- lib/shared-method.js
- test/rest.test.js
- test/shared-method.test.js
When a remote method returns a Promise, the return arguments that should affect status or header  properties are not handled properly
- #407 
> Remote method returned promise args do not respect http.target

- lib/rest-adapter.js
- lib/shared-class.js
- test/jsonrpc.test.js
- test/rest-adapter.test.js
- test/rest.test.js
- test/shared-class.test.js
Setting `"normalizeHttpPath"` in `confing.json` currently has no effect on models:
```json
"remoting": {
"rest": {
"normalizeHttpPath": true
}
}
```
This PR addresses this issue by implementing a proposal that @ritch has mentioned in a comment here:
https://github.com/strongloop/strong-remoting/blob/master/lib/shared-class.js#L64
strongloop/loopback#608
> Add support for app-wide "normalizeHttpPath"

- lib/http-context.js
- test/streams.js
when SSE connection is closed, destroy PassThrough stream created in createChangeStream()
> fix: destroy stream result on client close

- package.json
Update the version of the request dependency, due to a security issue in the tough-cookie library
> The tough-cookie module is vulnerable to regular expression denial of service. Input of around 50k characters is required for a slow down of around 2 seconds.
[tough-cookie vulnerability](https://nodesecurity.io/advisories/525)
[request update](https://github.com/request/request/pull/2776)
> Update minimum request version to enforce security fix in tough-cookie dependency

- .travis.yml
- package.json
Some of our dependencies are no longer supporting pre-4.0 versions of Node.js. As a result, our CI builds are failing on these platforms.
This pull request removes 0.10 and 0.12 from our Travis CI build matrix and also adds "engines" field to package.json to tell our internal Jenkins CI to stop testing 0.10 and 0.12 versions too.
While this may be seen as a controversial move and possibly as a breaking change, I think the impact should be minimum in practice. Both 0.10 and 0.12 versions are not maintained for more than 9 months by now, they are known to contain several security vulnerabilities. Nobody should be running them in production by now. Also note that the "engines" field is by default advisory only and npm install will succeed even on unsupported platforms - see …
> Drop support for Node.js versions 0.10 and 0.12 in 2.x branch

- lib/http-invocation.js
- lib/rest-adapter.js
- test/http-invocation.test.js
- test/rest-adapter.test.js
Allow the rest connector to call other loopback services by passing on the user authorization from the options where available. This is the fallback if no other authorization is specified.
This allows loopback servers to communicate securely with other loopback servers by passing on the auth token. Useful for using loopback as microservices.
- connect to strongloop/loopback-connector-rest#89
- connect to strongloop/loopback-connector-remote#3
- connect to #421 
> Add support for pass-through authentication 

- lib/http-context.js
- test/rest.test.js
Fixes a bug where loopback tries to set headers that have already been sent.
Note that express will strip out the `Content-Type` header if the response is 304:
https://github.com/expressjs/express/blob/351396f971280ab79faddcf9782ea50f4e88358d/lib/response.js#L208-L214
Loopback will try to set `Content-Type` to a default (typically `application/json`) if the header does not exist
https://github.com/strongloop/strong-remoting/blob/2153d183be457e8d8f76ca08b79fedb87b387b15/lib/http-context.js#L573-L575
This can lead to a weird edge case when doing tasks like rendering ejs where the following occurs:
Application:
- Tell res to render a template (e.g. an ejs page) from a remote method
Express
- Set some headers including `Content-Type: text/html` since we’re rendering ejs
- Realise that the …
> Avoid setting Content-Type on 304

- lib/remote-objects.js
- test/remote-objects.test.js
Add API allowing consumers (e.g. LoopBack) to remove shared class and
type converters (e.g. while removing a LoopBack Model).
- n/a
> feat: remove shared class & type converter

- lib/remote-objects.js
- test/remote-objects.test.js
fixing bug that when a class is deleted it's remote methods are not actually removed from app listener tree.
according to discussion [here](https://github.com/strongloop/loopback/pull/3922) this belongs to string remoting, so I reworked the changes here.
> Delete remote hooks when class is deleted

- lib/remote-objects.js
- test/type.test.js
deleteType to remove type from existing types. This is equivalent to deleteType for typeRegistry which exist in loopback 2.x 
- connect to #453 
> deleteType support in loopback 2.x

- package.json
See https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream
> Fixate event-stream version to 3.3.1

- package.json
See related discussion in https://github.com/strongloop/strong-remoting/pull/458
> Lock event-stream to 3.3.1 for 2.x

- README.md
- package.json
Related to https://github.com/strongloop/loopback/issues/4180
- Update `README` for the LTS status
- Update `package.json` `author` attribute so that the `slt copyright` command can generate the right copyright header
There are 89 files that need to be updated for the copyright headers, so I'll create a separate PR for that for easier review.
> update README for LTS status

- .travis.yml
- package.json
It has reached end-of-life long time ago plus `loopback` does no support
it either - see https://github.com/strongloop/loopback/pull/4194
> Drop support for Node.js 6.x

- lib/http-invocation.js
- lib/type-registry.js
- test/rest.browser.test.js
In LoopBack, the method `PersistedModel.updateAll` describes the return type using an inline (anonymous) definition:
```
{
returns: {
arg: 'info',
type: {
count: {
type: 'number',
description: 'The number of instances updated',
},
},
root: true,
},
}
```
Before this change, remote invocation of updateAll was crashing the process with the following error:
```
AssertionError: type must be either an array or a string.
```
This patch fixes the problem as follows:
- A try/catch block is introduced to correctly report any sync errors via the callback
- The type registry was improved to recognize anonymous object types and use the "object" converter for them.
Fixes https://github.com/strongloop/loopback/issues/3717
/cc @angfal @ewrayjohnson
> Fix handling of anonymous object types

- lib/rest-adapter.js
- test/rest-adapter.test.js
fixes #464
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/strong-remoting) 👈
Probably `loopback-swagger` needs an update too. Now that `route.http` is defined [route-helper](https://github.com/strongloop/loopback-swagger/blob/master/lib/specgen/route-helper.js#L213-L221) expects also `errorStatus` to be defined and displays an undefined error.
> Forward http definition to REST routes

- lib/shared-method.js
Fixes wrong type definitions in documentation for the arguments of `SharedMethod` and `SharedMethod.fromFunction`.
Fixes #462
> Fix misleaded property definitions

- lib/http-context.js
- test/rest.test.js
When response is a redirect (302 by default), for example `await options.httpContext.res.redirect(redirectUrl)` generates following error
```
(node:8972) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at ServerResponse.setHeader (_http_outgoing.js:541:11)
at ServerResponse.header (C:\Users\x\myProject\node_modules\express\lib\response.js:771:10)
at HttpContext.done (C:\Users\x\myProject\node_modules\strong-remoting\lib\http-context.js:574:9)
...
```
This PR makes _Content-Type_ header optional since message body is optional for redirects.
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/strong-remoting) 👈
> Content-Type should be optional for all 3xx redirects
