lib/shared-method.js, test/rest.test.js
=> Fix parsing JSON arrays with arrayItemDelimiters on.

lib/http-context.js, lib/http-invocation.js
/to @bajtos or @ritch 
/cc @bnoordhuis
=> Optimize the code to remove closure and bind

lib/rest-adapter.js, test/rest-adapter.test.js
Fixes https://github.com/strongloop/strong-remoting/issues/160
=> Handle Http Invoke Errors

example/simple.js
The examples are out of date. This corrects the simple example. The others should take the same approach.
Although before that I'd like to add some sugar APIs to make the examples a bit less redundant.
/to @raymondfeng @bajtos 
/cc @jakerella
=> Update simple example

lib/http-context.js
=> Remove use of deprecated `req.param()` in express

lib/http-context.js, test/http-context.test.js
See https://github.com/strongloop/strong-remoting/issues/143 and https://github.com/strongloop/strong-remoting/issues/167
/to @raymondfeng @bajtos 
/cc @BerkeleyTrue
=> Improve coercion for untyped args

lib/http-invocation.js, test/auth.test.js
/to @raymondfeng @bajtos please review
/cc @rmg
=> Add proper bearer token support and tests

lib/http-context.js, lib/http-invocation.js, test/auth.test.js, test/http-context.test.js, test/rest.test.js
@ritch Merging without review as these are simple fixes.
=> Fix JSCS errors

package.json
Just use `request` in the browser...
Close #192
@bajtos
=> Remove request-browser

lib/http-context.js, test/rest.test.js
Connect to strongloop/loopback#1276
=> Expose HttpContext as `req.remotingContext`

test/rest.test.js
/to @ritch @STRML please review
=> Fix typo introduced in fca2fb0

lib/http-context.js, test/rest.test.js
Adds support for application/vnd.api+json media type.
See discussion here: https://github.com/strongloop/loopback/issues/445#issuecomment-150923129
=> Support application/vnd.api+json media type

3.0-RELEASE-NOTES.md, lib/shared-class.js, lib/shared-method.js, test/shared-class.test.js, test/shared-method.test.js
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/617
See also https://github.com/strongloop/loopback/issues/597
=> Change method call to find remote method.

lib/http-context.js, lib/shared-method.js, test/rest.test.js
A back-port of #284 to 2.x
Fix strongloop/loopback#2063
=> Add support for "file" return args [2.x]

lib/rest-adapter.js, test/rest.test.js
Backport from strongloop/strong-remoting#289
connect to strongloop/loopback#2123
=> Handle array of errors.

lib/http-context.js, test/streams.js
Connect to https://github.com/strongloop/angular-live-set/issues/10
=> Set to no compression when using change stream

lib/http-invocation.js, lib/remote-objects.js
I used the latest version of `strong-docs` from `master` to verify the rendered output.
@richardpringle @0candy or @davidcheung please review
cc @ritch
=> Fix API docs in lib/remote-objects

lib/type-registry.js, lib/types/geopoint.js, package.json, test/rest-coercion/jsonbody-array.suite.js, test/rest-coercion/jsonbody-geopoint.suite.js, test/rest-coercion/jsonform-geopoint.suite.js, test/rest-coercion/urlencoded-geopoint.suite.js
Connect to #365 
**Update 17/11/16**:
- Blocked until new geopoint module is published
**Update 18/11/16**:
- Updated implementation to use new module, will rebase once new module is published on npm
=> Add coercion support for loopback data type: geopoint

lib/shared-class.js, test/shared-class.test.js
Backport of #385 
- strongloop/loopback#1936
=> Disable remote methods by alias

lib/types/geopoint.js, lib/types/object.js, package.json, test/authorize-hook.test.js
See https://github.com/strongloop/eslint-config-loopback/pull/19
=> Upgrade eslint-config, fix new violations

lib/remote-objects.js, test/remote-objects.test.js
Implemented a mechanism allowing strong-remoting users to provide their own transport/adapter implementations.
- #141 
=> Support custom transport/adapter implementations

.travis.yml
=> travis: drop Node.js 7.x, add 8.x

package.json
=> Update sse to 0.0.7

lib/http-context.js, lib/remote-objects.js, test/rest.test.js
Oops, there was a typo in my prior pull request #433
=> Fix typo in status code check

lib/jsonrpc-adapter.js, package.json
This fixes the following security vulnerability: 
- [npm:lodash:20180130](https://snyk.io/vuln/npm:lodash:20180130)
=> Upgrade jayson from 1.x to 2.x

lib/rest-adapter.js
Removed unnecessary extra whitespace
- connect to #373 
=> Removed extra whitespace

lib/jsonrpc-adapter.js, lib/remote-objects.js, lib/rest-adapter.js, lib/shared-class.js, lib/shared-method.js, package.json, test/e2e/smoke.test.js, test/http-invocation.test.js, test/rest-adapter.test.js, test/rest.browser.test.js, test/rest.test.js, test/shared-method.test.js
Fix comma-dangle violations
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/strong-remoting) 👈
=> chore: fix eslint violations

lib/http-context.js, test/streams.js
Fixes https://github.com/strongloop/strong-remoting/issues/482
Includes test case.
=> Json zombie streams
